### ISSUE TITLE
instanceOf ignores subclassing

### ISSUE THREAD

**Issue by bilbosan** [vadimdemedes/cancan#23]
I'm confused as to why you would make `instanceOf` so specific:

``` javascript
function instanceOf (instance, model) {
    return instance.constructor === model;
}
```

Because you use this (rather than the native browser's `instanceof`), many subclasses will not work. Example:

```
var cancan = require('cancan')
var Liquor = Backbone.Collection.extend({})
var Beer = Liquor.extend({})
var User = function() {}

cancan.configure(User, function(user) {  
  this.can('buy', Liquor)
})

var user = new User()
var liquor = new Liquor()
var beer = new Beer()

cancan.can(user, 'buy', liquor) // returns true
cancan.can(user, 'buy', beer) // returns false
```

I would expect subclasses to work, such that I don't have to configure every single subclass in `cancan.configure`.

**Comment by vdemedes** [comment]
Good point, would you be interested in making a PR?

**Comment by vadimdemedes** [comment]
Made this check more loose in v3.0.0. Check out the new v3's readme ;)
