### ISSUE TITLE
Use like middleware

### ISSUE THREAD

**Issue by yassinMk** [vadimdemedes/cancan#26]
Hi there, 
Is there a way to use the can method like a middleware ?

**Comment by vadimdemedes** [comment]
Could you provide an example?

**Comment by yassinMk** [comment]
`    router.get('/api/analytics', can(user, 'view', Analytic),
        function (req, res) {
            db.Analytic.findAll()
                .then(function (analytics) {
                    return res.json({ success: true, analytics: analytics });
                }).catch(function (err) {
                    return res.json({success: false});
                });
        }
    );
`

**Comment by vadimdemedes** [comment]
Nope, but I'm pretty sure you can do this easily manually. I try to not bundle extra or nice to have functionality to ease the maintenance.
