### ISSUE TITLE
Get rid of all dependencies

### ISSUE THREAD

**Issue by stalniy** [vadimdemedes/cancan#29]
1. `arrify` can be replaced with `Array.from` or `Array#concat`
```js
function arrify(value) {
  return [].concat(value || [])
}
```
2. `is-plain-obj` can be replaced with simple check
```js
function isObject(value) {
  return value && value.constructor === Object
}
```
3. `auto-bind` can be replaced with `['can', 'cannot', 'allow'].forEach(method => this[method] = this[method].bind(this))`. Also you don't need to bind everything but only specific methods.

All this will make installation faster, no need to do `npm install`

**Comment by vadimdemedes** [comment]
The sizes of these dependencies are so tiny they're hardly noticeable. Also, see https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328.
