### ISSUE TITLE
Retrieve conditions object for view permissions

### ISSUE THREAD

**Issue by ackerdev** [vadimdemedes/cancan#3]
A method on the cancan object that accepts a user instance and a resource class, and returns the conditions object from the rules for that resource.

Users can then use that object to insert filters into their querying-software-of-choice, making it simple to provide appropriately scoped collections of a resource.

**Comment by vadimdemedes** [comment]
Closing, most likely not going to implement this. It can't work universally for all conditions, because they can be functions, not only objects.
